/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.OrganBankEnterprise;
import Business.Network.Network;
import Business.Organization.Facilities;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrganProcureWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saras
 */
public class OrganManagement extends javax.swing.JPanel {

    /**
     * Creates new form OrganManagement
     */
     JPanel userProcessContainer;
    OrganizationDirectory organizationDirectory; 
    Enterprise enterprise;
    EcoSystem ecoSystem;
    Network network;
    
    public OrganManagement(JPanel userProcessContainer, OrganizationDirectory organizationDirectory, Enterprise enterprise,EcoSystem ecoSystem,Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organizationDirectory=organizationDirectory;
        this.enterprise=enterprise;
        this.ecoSystem=ecoSystem;
        this.network=network;
        
        initComponents();
        populateJTable();
        populateComboBox();
        //initcb_dept();
       // txt_patId.setText(""+this.ecoSystem.getPatientId());   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganworkRequests = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        cmbxfacalities = new javax.swing.JComboBox<>();
        btnProcure = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        tblOrganworkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "OrgansRequired", "Doctor", "Comments", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganworkRequests);

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        cmbxfacalities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbxfacalities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxfacalitiesActionPerformed(evt);
            }
        });

        btnProcure.setText("Procure");
        btnProcure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcureActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient", "Status", "OrgansRequired", "Patient", "Doctor"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Organ Procurement Requests");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnProcure, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(cmbxfacalities, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcure)
                    .addComponent(cmbxfacalities, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssign))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcureActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblOrganworkRequests.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        OrganProcureWorkRequest orgwr = (OrganProcureWorkRequest)tblOrganworkRequests.getValueAt(selectedRow, 0);
        if(orgwr.getStatus().equalsIgnoreCase("procurement requested")) {
            orgwr.setStatus("Work Started");
            //order.setAssign(true);
        }
        
        
        
        else {
            JOptionPane.showMessageDialog(null, "Order is already ready Procured");
            return;
        }
        
         populateJTable();
    }//GEN-LAST:event_btnProcureActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        
         if(cmbxfacalities.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select a Procurement Team");
            return;
        }
        int selectedRow = tblOrganworkRequests.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Select request to assign Procurement", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        OrganProcureWorkRequest orgwr = (OrganProcureWorkRequest)tblOrganworkRequests.getValueAt(selectedRow, 0);
        
        if(!orgwr.getStatus().equals("Work Started")){
        JOptionPane.showMessageDialog(null,"Request should be procured first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
       /* order.setDeliveryMan(jcombodeliveryMan.getSelectedItem().toString());
        order.setOrderStatus("Order Picked up");
        variable= true;
        populateTable();*/
        for(Organization orga  : organizationDirectory.getOrganizationList()) {
           
           if( orga instanceof Facilities){
               //System.out.println(orga.getName()+":"+((Facilities) orga).getCounter());
               if(orga.getName().equalsIgnoreCase(cmbxfacalities.getSelectedItem().toString())){
                   orga.getWorkQueue().getWorkRequestList().add((OrganProcureWorkRequest)tblOrganworkRequests.getValueAt(selectedRow, 0));
                   ((Facilities) orga).setCounter(1);
                   
               }
           }
           
            
        
    }
      orgwr.setStatus("Assigned");
      orgwr.setTeam(cmbxfacalities.getSelectedItem().toString());
      populateJTable();
      populateComboBox();
        
       
    }//GEN-LAST:event_btnAssignActionPerformed

    private void cmbxfacalitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxfacalitiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxfacalitiesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populateJTable() {
       /*  OrganProcureWorkRequest request = new OrganProcureWorkRequest();
        request.setPatientAccount(patAccount(workRequestJTable.getValueAt(workRequestJTable.getSelectedRow(), 0).toString()));
        
        ArrayList<String> orList=new ArrayList<>();
        if(chk_heart.isSelected()){
            orList.add("Heart");
        }
        if(chk_kidney.isSelected()){
            orList.add("Kidney");
        }
        if(chk_liver.isSelected()){
            orList.add("Liver");
        }
        if(chk_pancreas.isSelected()){
            orList.add("Pancreas");
        }
        request.setOrganList(orList);
        request.setSender(userAccount);
        request.setStatus("Sent");
        
      
        // Enterprise ent = null;*/
        //System.out.println(enterprise.getOrganizationDirectory().getOrganizationList()+"yay");
        DefaultTableModel model = (DefaultTableModel) tblOrganworkRequests.getModel();
         model.setRowCount(0);
         for(Network n: ecoSystem.getNetworkList()){

            if(n.getName().equalsIgnoreCase(network.getName())) {
             
             
             
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof OrganBankEnterprise){
                    //ent=e;
                   // ent.getWorkQueue().getWorkRequestList().add(request);
                    //userAccount.getWorkQueue().getWorkRequestList().add(request);
                    if(e.getWorkQueue()== null){
                        System.out.println("catched by repears");
                      break;}
                    for(WorkRequest wr: e.getWorkQueue().getWorkRequestList()){
                        //System.out.println("size"+e.getWorkQueue().getWorkRequestList().size());
                        if(!(wr.getStatus() ==null)){
                        if(wr.getStatus().equalsIgnoreCase("procurement requested") ||wr.getStatus().equalsIgnoreCase("work started")|| wr.getStatus().equalsIgnoreCase("Assigned") ||wr.getStatus().equalsIgnoreCase("InProcess")|| wr.getStatus().equalsIgnoreCase("Completed")){
                            OrganProcureWorkRequest opr = (OrganProcureWorkRequest)wr;
                            System.out.println("In Ark space ship");
                            String a ="";
                            for( String s: opr.getOrganList()){
                                a= s+":"+a;
                            }
                            Object[] row = new Object[80];
                        row[0]= opr;
                        //row[1] = opr.getMessage();
                        row[1]=opr.getPatient().getName();
                        row[2] = a;
                        row[3] = opr.getPatient().getDoctor();
                        row[4] = opr.getMessage();
                        row[5] = opr.getStatus();
                        model.addRow(row);
                        //break;
                        }}
                        else{
                        }
                      
                     
                    
                    }
                }
            }
            }
        }
        
               /* row[0] = order;
                row[1] = order.getCustomer().getName();
                row[2] = order.getCustomer().getHomeAddress();
                row[3] = order.getRestaurant().getRestaurantName();
                row[4] = order.getRestaurant().getAddress();
                row[5] = order.getOrderStatus();
                model.addRow(row);*/
        /**
         * DefaultTableModel model = (DefaultTableModel) tblDeliveryMan.getModel();
        model.setRowCount(0);
       // System.out.println("Hi");
        //System.out.println(("siva"+userAccount.getEmployee().getName()));
        for (Order order : business.getOrderDirectory().getOrderDirectory()) {
            
            //System.out.println("sai"+userAccount.getUsername());
            //System.out.println("siva 2");
           // System.out.println(order.getDeliveryMan()+"Rams");
           // System.out.println(userAccount.getUsername()+"kioo");
          
            
            if (order.getDeliveryMan().equals(userAccount.getUsername())) {
               // System.out.println("Vety Imp");
                Object[] row = new Object[6];
                row[0] = order;
                row[1] = order.getCustomer().getName();
                row[2] = order.getCustomer().getHomeAddress();
                row[3] = order.getRestaurant().getRestaurantName();
                row[4] = order.getRestaurant().getAddress();
                row[5] = order.getOrderStatus();
                model.addRow(row);
            }
        }
         */
        
       
        JOptionPane.showMessageDialog(null, "Organ Procurement Requested");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnProcure;
    private javax.swing.JComboBox<String> cmbxfacalities;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblOrganworkRequests;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
    }

    private void populateComboBox() {
        
        cmbxfacalities.removeAllItems();
        cmbxfacalities.addItem("--Select--");
        for(Organization orga  : organizationDirectory.getOrganizationList()) {
           
           if( orga instanceof Facilities){
               if(((Facilities) orga).getCounter()==0){
               cmbxfacalities.addItem(orga.getName());}
           }
           
            
        
    }}
}
