/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Person.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chandrasekhar
 */
public class PatientManagement extends javax.swing.JPanel {

    JPanel userProcessContainer;
    OrganizationDirectory organizationDirectory; 
    Enterprise enterprise;
    /**
     * Creates new form PatientManagement
     */
    public PatientManagement(JPanel userProcessContainer, OrganizationDirectory organizationDirectory, Enterprise enterprise) {
        this.userProcessContainer=userProcessContainer;
        this.organizationDirectory=organizationDirectory;
        this.enterprise=enterprise;
        
        initComponents();
        initcb_dept();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_patId = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        cb_dept = new javax.swing.JComboBox<>();
        cb_doctor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_phnNum = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setText("Patient Details");

        jLabel2.setText("Patient ID :");

        jLabel3.setText("Name :");

        jLabel4.setText("Age :");

        jLabel5.setText("Speciality :");

        jLabel6.setText("Doctor :");

        cb_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_deptActionPerformed(evt);
            }
        });

        cb_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_doctorActionPerformed(evt);
            }
        });

        jLabel7.setText("Phone Number :");

        btn_save.setText("Submit");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_patId)
                                    .addComponent(txt_name)
                                    .addComponent(txt_age)
                                    .addComponent(cb_dept, 0, 224, Short.MAX_VALUE)
                                    .addComponent(cb_doctor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_phnNum)))
                            .addComponent(btn_save, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_back, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_patId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_phnNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btn_save)
                .addGap(34, 34, 34)
                .addComponent(btn_back)
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void initcb_dept(){
        cb_dept.addItem("--Select--");
        for(Organization org: organizationDirectory.getOrganizationList()){
            if(org.getType().getValue().equalsIgnoreCase("medical")){
                cb_dept.addItem(org.getName());
            }
        }
    }
    
    
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        if(txt_name.getText().isEmpty() || txt_age.getText().isEmpty() || txt_phnNum.getText().isEmpty() ||
               cb_dept.getSelectedIndex()==0||cb_doctor.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null, "Please provide details in all fields");
            return;
        }
        //firstname and last name===========================
        boolean check ; 
        check = txt_name.getText().matches("^[a-zA-Z]+$");
        
        if(check == false) {
            JOptionPane.showMessageDialog(null, "First name cannot have numerics");
            return;
        }

        //Phone Number==================================================
        
        if(txt_phnNum.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "PhoneNumber must be of 10 digits");
            return;
        }
        check = txt_phnNum.getText().matches("^[0-9]+$");
        if(!check) {
            JOptionPane.showMessageDialog(null, "Phone Number must have digits only");
            return;
        }
        //Age========================================
        check=txt_age.getText().matches("^[1-9][0-9]?$");
        if(!check){
            JOptionPane.showMessageDialog(null, "Please enter a proper age value");
            return;
        }

        //Organization organization = (Organization) cb_dept.getSelectedItem();
        //JOptionPane.showMessageDialog(null, cb_dept.getSelectedItem());
        //JOptionPane.showMessageDialog(null, organization.getName());
        
        for(int i=0;i<organizationDirectory.getOrganizationList().size();i++){
            if(organizationDirectory.getOrganizationList().get(i).getName().equalsIgnoreCase(cb_dept.getSelectedItem().toString())){
                Organization organization=organizationDirectory.getOrganizationList().get(i);
                JOptionPane.showMessageDialog(null, organization.getPatientDirectory());
                organization.getPatientDirectory().createPatient(Integer.parseInt(txt_patId.getText()),txt_name.getText(),txt_age.getText(),txt_phnNum.getText(),cb_dept.getSelectedItem().toString(),cb_doctor.getSelectedItem().toString(),true,false,false);
                break;
            }
        }
        
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void cb_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_doctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_doctorActionPerformed

    private void cb_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_deptActionPerformed
        // TODO add your handling code here:
        cb_doctor.removeAllItems();
        cb_doctor.addItem("--Select--");
        int counter=0;
        for(int i=0;i<organizationDirectory.getOrganizationList().size();i++){
            Organization org=organizationDirectory.getOrganizationList().get(i);
            //JOptionPane.showMessageDialog(null, cb_dept.getSelectedItem().toString().equalsIgnoreCase(org.getName()));
            if(cb_dept.getSelectedItem().toString().equalsIgnoreCase(org.getName())){
                for(int j=0;j<org.getUserAccountDirectory().getUserAccountList().size();j++){
                    Employee emp=org.getUserAccountDirectory().getUserAccountList().get(j).getEmployee();
                    cb_doctor.addItem(emp.getName());
                    counter++;
                }
            }
        }
        if(counter==0){
            cb_doctor.removeAllItems();
            cb_doctor.addItem("No Doctors");
        }
    }//GEN-LAST:event_cb_deptActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cb_dept;
    private javax.swing.JComboBox<String> cb_doctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_patId;
    private javax.swing.JTextField txt_phnNum;
    // End of variables declaration//GEN-END:variables
}
