/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabAssistantRole;

import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mruna
 */
public class ProcessDiagnostics extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest request;
    private String others;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessDiagnostics(JPanel userProcessContainer, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        initlables();

    }

    public void initlables() {
   
        jLabel2.setVisible(false);
        cb_test1.setVisible(false);
        jLabel3.setVisible(false);
        cb_test2.setVisible(false);
        jLabel4.setVisible(false);
        cb_test3.setVisible(false);
        jLabel5.setVisible(false);
        cb_test4.setVisible(false);
        System.out.println("Test Array in lab procewss"+request.getTests());
        for (String s : request.getTests()) {
           
          
            if (s.equalsIgnoreCase("")) {
                jLabel2.setVisible(true);
                cb_test1.setVisible(true);

            }
            if (s.equalsIgnoreCase("")) {
                jLabel4.setVisible(true);
                cb_test3.setVisible(true);
            }
            if (s.equalsIgnoreCase("")) {
                jLabel3.setVisible(true);
                cb_test2.setVisible(true);
            }
            if (!(s.equalsIgnoreCase("") || s.equalsIgnoreCase("") || s.equalsIgnoreCase(""))) {
                jLabel5.setVisible(true);
                jLabel5.setText(s);
                cb_test4.setVisible(true);
                others=s;

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_genres = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_resultcomment = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_test1 = new javax.swing.JComboBox();
        cb_test2 = new javax.swing.JComboBox();
        cb_test3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cb_test4 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btn_genres.setBackground(new java.awt.Color(0, 51, 102));
        btn_genres.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_genres.setForeground(new java.awt.Color(255, 255, 255));
        btn_genres.setText("Generate Result");
        btn_genres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genresActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Result:");

        txt_resultcomment.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        btn_back.setBackground(new java.awt.Color(0, 51, 102));
        btn_back.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Previous");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Blood Typing");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Test-2");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Test-3");

        cb_test1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cb_test1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Normal ", "Abnormal", " " }));

        cb_test2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cb_test2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Normal ", "Abnormal", " " }));
        cb_test2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_test2ActionPerformed(evt);
            }
        });

        cb_test3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cb_test3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Normal ", "Abnormal", " " }));
        cb_test3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_test3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Random:");

        cb_test4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cb_test4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Normal ", "Abnormal", " " }));
        cb_test4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_test4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LAB TESTS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(btn_back))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_test1, 0, 146, Short.MAX_VALUE)
                                .addComponent(cb_test2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_test3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_test4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_resultcomment))
                            .addComponent(btn_genres, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_test1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cb_test2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_test3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cb_test4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_resultcomment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back)
                    .addComponent(btn_genres))
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DiagnosticsWorkArea dwjp = (DiagnosticsWorkArea) component;
        dwjp.initWorktable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_genresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genresActionPerformed
        request.setTestResult(txt_resultcomment.getText());
        request.setStatus("Completed");
        String test1 = cb_test1.getSelectedItem().toString();    
        String test2 = cb_test2.getSelectedItem().toString();
        String test3 = cb_test3.getSelectedItem().toString();
        String test4 = cb_test4.getSelectedItem().toString();

        
 JOptionPane.showMessageDialog(null,"Report has been sent");

    }//GEN-LAST:event_btn_genresActionPerformed

    private void cb_test3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_test3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_test3ActionPerformed

    private void cb_test4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_test4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_test4ActionPerformed

    private void cb_test2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_test2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_test2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_genres;
    private javax.swing.JComboBox cb_test1;
    private javax.swing.JComboBox cb_test2;
    private javax.swing.JComboBox cb_test3;
    private javax.swing.JComboBox cb_test4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_resultcomment;
    // End of variables declaration//GEN-END:variables
}
