/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthOfficer;

import Business.EcoSystem;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Mrunal <your.name at your.org>
 */
public class LoadWebPage extends javax.swing.JPanel {

    /**
     * Creates new form LoadWebPage
     */
    private JPanel userProcessContainer;

    private EcoSystem system;

    public LoadWebPage(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        //this.userProcessContainer = userProcessContainer;
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        final JFrame frame = new JFrame();

        frame.setSize(620, 440);
        final JFXPanel fxpanel = new JFXPanel();
        frame.add(fxpanel);

        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                WebEngine engine;
                WebView wv = new WebView();
                engine = wv.getEngine();
                fxpanel.setScene(new Scene(wv));
                engine.load("https://www.mass.gov/orgs/massachusetts-health-policy-commission");
            }
        });
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
